# Generated by Django 4.1 on 2022-09-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
