export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'


export const USER_LOGOUT = 'USER_LOGOUT'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCESS = 'REGISTER_SUCESS'
export const REGISTER_REJECTED = 'REGISTER_REJECTED'


export const USERPROFILE_REQUEST = 'USERPROFILE_REQUEST'
export const USERPROFILE_SUCCESS = 'USERPROFILE_SUCCESS'
export const USERPROFILE_REJECTED = 'USERPROFILE_REJECTED'
export const USERPROFILE_RESET = 'USERPROFILE_RESET'


export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'